import 'package:simlimites/models/sim/esim_models.dart';

class DataServices {
  static String iconPlanAssetsRoute = 'assets/';

  static List<SimCountries> countriesList = [
    //local
    SimCountries(
      productId: 'productId',
      productName: 'Estados Unidos',
      shortDescription: 'Plan de datos y llamadas',
      fromPrice: '10',
      fullDescription:
          'Con sólo un código QR que escaneas en tu dispositivo, podrás tener un plan de datos instantáneamente en Estados Unidos con internet ilimitado 4G/5G en todo momento y llamadas ilimitadas en este territorio.',
      cardImage: iconPlanAssetsRoute + 'backgrounds_plans/usa.jpg',
      productType: 'local',
      characteristics: const [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación',
      ],
      coverage: const [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Saint Thomas '),
        Coverage(image: '/path', name: 'Puerto Rico'),
        Coverage(image: '/path', name: 'Santa Cruz'),
      ],
      flagIcon: iconPlanAssetsRoute + 'usa.png',
      planes: const [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Puerto Rico',
      shortDescription: 'Plan de datos y llamadas',
      fullDescription: 'fullDescription',
      fromPrice: '10',
      productType: 'local',
      cardImage: iconPlanAssetsRoute + 'backgrounds_plans/pr.jpg',
      characteristics: const [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación',
      ],
      coverage: const [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      flagIcon: iconPlanAssetsRoute + 'colombia.png',
      planes: const [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Canadá',
      shortDescription: 'Plan de datos y llamadas',
      fromPrice: '10',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: iconPlanAssetsRoute + 'backgrounds_plans/canada.jpg',
      characteristics: const [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: const [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      flagIcon: iconPlanAssetsRoute + 'canada.png',
      planes: const [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'México',
      fromPrice: '10',
      shortDescription: 'Plan de datos y llamadas',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: iconPlanAssetsRoute + 'backgrounds_plans/mex.jpg',
      characteristics: const [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: const [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      flagIcon: iconPlanAssetsRoute + 'mexico.png',
      planes: const [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    /*
    SimCountries(
      productId: 'productId',
      productName: 'Perú',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage:
          'https://cdn-appfo.nitrocdn.com/ezpwpnlIhXXnOemnkjdVuXlnpuBbpFkh/assets/static/optimized/rev-3978c0c/wp-content/uploads/2021/07/Peru-1024x1024.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: 'assets/peru.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Argentina',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage:
          'https://cdn-appfo.nitrocdn.com/ezpwpnlIhXXnOemnkjdVuXlnpuBbpFkh/assets/static/optimized/rev-3978c0c/wp-content/uploads/2019/11/Plan-Argentina-sim-limites-1024x1024.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: iconPlanAssetsRoute + 'argentina.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Australia',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: 'assets/ship.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: iconPlanAssetsRoute + 'australia.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Alemania',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: 'assets/ship.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: iconPlanAssetsRoute + 'germany.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Brasil',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: 'assets/ship.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: iconPlanAssetsRoute + 'brazil.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Belgica',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: 'assets/ship.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: iconPlanAssetsRoute + 'belgium.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Chile',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: 'assets/ship.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: iconPlanAssetsRoute + 'chile.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    SimCountries(
      productId: 'productId',
      productName: 'Costa Rica',
      shortDescription: 'shortDescription',
      fullDescription: 'fullDescription',
      productType: 'local',
      cardImage: 'assets/ship.png',
      characteristics: [
        'Llamadas ilimitadas en país de cobertura',
        'Datos ilimitados en 4G LTE (sin degradación)',
      ],
      coverage: [
        Coverage(image: '/path', name: 'Estados Unidos'),
        Coverage(image: '/path', name: 'Alaska'),
        Coverage(image: '/path', name: 'Hawai'),
        Coverage(image: '/path', name: 'Islas Vírgenes de EE. UU. '),
        Coverage(image: '/path', name: 'Puerto Rico'),
      ],
      image: iconPlanAssetsRoute + 'costa-rica.png',
      planes: [
        PlanData(price: 23, currentyType: 'USD', days: '5', gbCount: '5GB'),
        PlanData(price: 30, currentyType: 'USD', days: '7', gbCount: '20GB'),
        PlanData(price: 35, currentyType: 'USD', days: '15', gbCount: '35GB'),
        PlanData(price: 45, currentyType: 'USD', days: '30', gbCount: '45GB'),
        PlanData(price: 100, currentyType: 'USD', days: '60', gbCount: '120GB'),
      ],
    ),
    */
  ];
}
